Adding security scan step in arc diff workflow
robinhoodmarkets/arcanist pull request #16
Opened 2023-02-01 23:13 UTC by rishindraw

This security step is set to run in the background within the arc diff workflow. We setup a timeout of 15 seconds for this command to handle latency scenarios. Our plan is to let it run in the background for a while and collect the execution data to enhance the product before enforcing it completely.

2023-02-01 23:25 UTC, rishindraw commented
Tested locally and verified changes to be working as expected.

2023-02-01 23:30 UTC, xiciluan commented
> Tested locally and verified changes to be working as expected.

Could you specify the scenarios you've tested in more detail? Also want to confirm you tested it for both sherwood and arcanist users. Another questions is, are we going to enable this for all repos or just rh monorepo?

2023-02-01 23:40 UTC, Aghassi requested changes

2023-02-01 23:40 UTC, Aghassi commented on scripts/secscan_scan_pre_push.sh
> +    exit 0
is this ever a possibility?

2023-02-01 23:40 UTC, Aghassi commented on scripts/secscan_scan_pre_push.sh
> +bazel run --ui_event_filters=-info,-stdout,-stderr --noshow_progress //secscan -- scan -d ${HOME}/robinhood/rh/ -s=pre-commit
can we fire off a metric before and after this to pushgateway to ensure we have a start and stop time for this so we can monitor the runtime on user machines?

2023-02-01 23:40 UTC, Aghassi commented on src/workflow/ArcanistDiffWorkflow.php
> +    // TODO ProdSec: Handle exit code and stderr after monitoring phase is complete
failing silently feels risky, can we handle now?

2023-02-01 23:43 UTC, rishindraw commented on scripts/secscan_scan_pre_push.sh
> +    exit 0
if we remove this check it would be a breaking change. Added this check to be mindful that this is public repo.

2023-02-01 23:47 UTC, rishindraw commented on scripts/secscan_scan_pre_push.sh
> +bazel run --ui_event_filters=-info,-stdout,-stderr --noshow_progress //secscan -- scan -d ${HOME}/robinhood/rh/ -s=pre-commit
We have plans to do so as part of next iteration. First we want to enable it and start reporting metrics later. Do not want to introduce too big of a change at once.

2023-02-01 23:48 UTC, rishindraw commented on src/workflow/ArcanistDiffWorkflow.php
> +    // TODO ProdSec: Handle exit code and stderr after monitoring phase is complete
We are planning on adding alerts to errors which will be handled on security end.

2023-02-01 23:49 UTC, rishindraw commented
This change is solely to run this process in the background and monitor the execution. Just an FYI.

2023-02-02 00:53 UTC, ragona commented on scripts/secscan_scan_pre_push.sh
> +    exit 0
Where does `${EMAIL}` even come from? If it's the git config then we don't get any guarantee that this is even configured.

2023-02-02 18:49 UTC, rishindraw commented on scripts/secscan_scan_pre_push.sh
> +    exit 0
it's baked into `zshenv` through ahoy

2023-02-02 18:51 UTC, rishindraw commented
This PR needs to be redone so closing it.

2023-02-02 18:51 UTC, closed without merging

2023-02-06 16:01 UTC, joeljeske commented on scripts/secscan_scan_pre_push.sh
> +bazel run --ui_event_filters=-info,-stdout,-stderr --noshow_progress //secscan -- scan -d ${HOME}/robinhood/rh/ -s=pre-commit
Lets not assume that the user is in ~/robinhood/rh. I know that many users have more than one checkout of rh, and it may not be in that directory

The program being run by bazel (e.g. //secscan) can use the env var `BUILD_WORKSPACE_DIRECTORY` or you can get it `git rev-parse --show-toplevel` and pass it in as an arg.

2023-02-06 23:37 UTC, rishindraw commented on scripts/secscan_scan_pre_push.sh
> +bazel run --ui_event_filters=-info,-stdout,-stderr --noshow_progress //secscan -- scan -d ${HOME}/robinhood/rh/ -s=pre-commit
Thank you for pointing it out. I will update accordingly.