[DevX] Default to rebase to stable branch before running arc diff
robinhoodmarkets/arcanist pull request #4
Opened 2021-11-11 19:20 UTC by xiciluan

SW-ID-a5f5497f7d

2021-11-11 19:22 UTC, xiciluan commented on src/workflow/ArcanistDiffWorkflow.php
> +      exec('rm -fr ".git/rebase-merge"');
This is for resolving this error `fatal: It seems that there is already a rebase-merge directory`

2021-11-11 19:42 UTC, ptarjan requested changes

2021-11-11 19:42 UTC, ptarjan commented on src/workflow/ArcanistDiffWorkflow.php
>          'help'  => pht('Rebase to stable before creating diff.'),
```suggestion
        'help'  => pht('Do not rebase to the origin/stable branch before creating a diff.'),
```

2021-11-11 19:42 UTC, ptarjan commented on src/workflow/ArcanistDiffWorkflow.php
> +      exec('rm -fr ".git/rebase-merge"');
This seems bad. It means there was a previous rebase going on and you need to run `git rebase --abort`. I don't think you want to include this.

2021-11-11 19:42 UTC, ptarjan commented on src/workflow/ArcanistDiffWorkflow.php
> +          echo "Please run 'arc rebase' and follow above console outputs to resolve all conflicts manually. \n";
```suggestion
          echo "Please resolve the rebase conflicts in your editor and then run `git rebase --continue`. Then you can run `arc diff` again. \n";
```

2021-11-12 03:29 UTC, xiciluan commented on src/workflow/ArcanistDiffWorkflow.php
> +      exec('rm -fr ".git/rebase-merge"');
When simply running `arc diff` (with the change) everything's fine. When running `sw diff`, this error is raised while there is no actual rebase in progress, not sure if there's some rebase logic already in sherwood, will take further look tmr.

2022-03-02 20:55 UTC, closed without merging